//
// CallsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class CallsAPI: APIBase {
    /**
     Create a new call under the account.
     
     - parameter fonenumber: (form) FracTEL phone number to use as caller. 
     - parameter to: (form) Phone number to call. 
     - parameter tts: (form) Text to speech message. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func postCalls(fonenumber fonenumber: String, to: String, tts: String? = nil, completion: ((data: String?, error: ErrorType?) -> Void)) {
        postCallsWithRequestBuilder(fonenumber: fonenumber, to: to, tts: tts).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create a new call under the account.
     - POST /calls
     - Returns a JSON response
     - examples: [{contentType=application/json, example="aeiou"}]
     
     - parameter fonenumber: (form) FracTEL phone number to use as caller. 
     - parameter to: (form) Phone number to call. 
     - parameter tts: (form) Text to speech message. (optional)

     - returns: RequestBuilder<String> 
     */
    public class func postCallsWithRequestBuilder(fonenumber fonenumber: String, to: String, tts: String? = nil) -> RequestBuilder<String> {
        let path = "/calls"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "fonenumber": fonenumber,
            "to": to,
            "tts": tts
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     * enum for parameter method
     */
    public enum Method_postCallsReceiveNotify: String { 
        case Get = "GET"
        case Post = "POST"
        case Json = "JSON"
    }

    /**
     Configure the callback URL to notify when a call is received.
     
     - parameter fonenumber: (form) Your FracTEL phone number. 
     - parameter method: (form) Callback URL method. 
     - parameter url: (form) Callback URL. 
     - parameter urlUsername: (form) Callback URL username. (optional)
     - parameter urlPassword: (form) Callback URL password. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func postCallsReceiveNotify(fonenumber fonenumber: String, method: Method_postCallsReceiveNotify, url: String, urlUsername: String? = nil, urlPassword: String? = nil, completion: ((data: String?, error: ErrorType?) -> Void)) {
        postCallsReceiveNotifyWithRequestBuilder(fonenumber: fonenumber, method: method, url: url, urlUsername: urlUsername, urlPassword: urlPassword).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Configure the callback URL to notify when a call is received.
     - POST /calls/receive_notify
     - Returns a JSON response
     - examples: [{contentType=application/json, example="aeiou"}]
     
     - parameter fonenumber: (form) Your FracTEL phone number. 
     - parameter method: (form) Callback URL method. 
     - parameter url: (form) Callback URL. 
     - parameter urlUsername: (form) Callback URL username. (optional)
     - parameter urlPassword: (form) Callback URL password. (optional)

     - returns: RequestBuilder<String> 
     */
    public class func postCallsReceiveNotifyWithRequestBuilder(fonenumber fonenumber: String, method: Method_postCallsReceiveNotify, url: String, urlUsername: String? = nil, urlPassword: String? = nil) -> RequestBuilder<String> {
        let path = "/calls/receive_notify"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "fonenumber": fonenumber,
            "method": method.rawValue,
            "url": url,
            "url_username": urlUsername,
            "url_password": urlPassword
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     * enum for parameter method
     */
    public enum Method_postCallsSendNotify: String { 
        case Get = "GET"
        case Post = "POST"
        case Json = "JSON"
    }

    /**
     Configure the callback URL to notify when a call is made.
     
     - parameter fonenumber: (form) Your FracTEL phone number 
     - parameter method: (form) Callback URL method. 
     - parameter url: (form) Callback URL. 
     - parameter urlUsername: (form) Callback URL username. (optional)
     - parameter urlPassword: (form) Callback URL password. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func postCallsSendNotify(fonenumber fonenumber: String, method: Method_postCallsSendNotify, url: String, urlUsername: String? = nil, urlPassword: String? = nil, completion: ((data: String?, error: ErrorType?) -> Void)) {
        postCallsSendNotifyWithRequestBuilder(fonenumber: fonenumber, method: method, url: url, urlUsername: urlUsername, urlPassword: urlPassword).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Configure the callback URL to notify when a call is made.
     - POST /calls/send_notify
     - Returns a JSON response
     - examples: [{contentType=application/json, example="aeiou"}]
     
     - parameter fonenumber: (form) Your FracTEL phone number 
     - parameter method: (form) Callback URL method. 
     - parameter url: (form) Callback URL. 
     - parameter urlUsername: (form) Callback URL username. (optional)
     - parameter urlPassword: (form) Callback URL password. (optional)

     - returns: RequestBuilder<String> 
     */
    public class func postCallsSendNotifyWithRequestBuilder(fonenumber fonenumber: String, method: Method_postCallsSendNotify, url: String, urlUsername: String? = nil, urlPassword: String? = nil) -> RequestBuilder<String> {
        let path = "/calls/send_notify"
        let URLString = SwaggerClientAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "fonenumber": fonenumber,
            "method": method.rawValue,
            "url": url,
            "url_username": urlUsername,
            "url_password": urlPassword
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<String>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

}
