# coding: utf-8

"""
    FoneStorm API 2.4.0 (Thunder)

    FracTEL's Middleware API

    OpenAPI spec version: 2.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_9 import InlineResponse2009


class TestInlineResponse2009(unittest.TestCase):
    """ InlineResponse2009 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2009(self):
        """
        Test InlineResponse2009
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.inline_response_200_9.InlineResponse2009()
        pass


if __name__ == '__main__':
    unittest.main()
