# coding: utf-8

"""
    FoneStorm API 2.2.0 (Breeze)

    FracTEL's Middleware API

    OpenAPI spec version: 2.2.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.survey import Survey


class TestSurvey(unittest.TestCase):
    """ Survey unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSurvey(self):
        """
        Test Survey
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.survey.Survey()
        pass


if __name__ == '__main__':
    unittest.main()
