# coding: utf-8

"""
    FoneStorm API 2.4.0 (Thunder)

    FracTEL's Middleware API

    OpenAPI spec version: 2.4.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.campaigns_api import CampaignsApi


class TestCampaignsApi(unittest.TestCase):
    """ CampaignsApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.campaigns_api.CampaignsApi()

    def tearDown(self):
        pass

    def test_create_campaign(self):
        """
        Test case for create_campaign

        Create Campaign
        """
        pass

    def test_create_campaign_0(self):
        """
        Test case for create_campaign_0

        Create Campaign
        """
        pass

    def test_delete_campaign(self):
        """
        Test case for delete_campaign

        Delete Campaign
        """
        pass

    def test_delete_campaign_0(self):
        """
        Test case for delete_campaign_0

        Delete Campaign
        """
        pass

    def test_get_campaign(self):
        """
        Test case for get_campaign

        Get Campaign
        """
        pass

    def test_get_campaign_0(self):
        """
        Test case for get_campaign_0

        Get Campaign
        """
        pass

    def test_get_campaigns(self):
        """
        Test case for get_campaigns

        Get Campaigns
        """
        pass

    def test_get_campaigns_0(self):
        """
        Test case for get_campaigns_0

        Get Campaigns
        """
        pass

    def test_update_campaign(self):
        """
        Test case for update_campaign

        Update Campaign
        """
        pass

    def test_update_campaign_0(self):
        """
        Test case for update_campaign_0

        Update Campaign
        """
        pass


if __name__ == '__main__':
    unittest.main()
