<?php
/**
 * AccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FoneStorm API 2.2.0 (Breeze)
 *
 * FracTEL's Middleware API
 *
 * OpenAPI spec version: 2.2.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AccountTest Class Doc Comment
 *
 * @category    Class */
// * @description Account
/**
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AccountTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Account"
     */
    public function testAccount()
    {
    }

    /**
     * Test attribute "background_color"
     */
    public function testPropertyBackgroundColor()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "cdr_notify_url"
     */
    public function testPropertyCdrNotifyUrl()
    {
    }

    /**
     * Test attribute "cdr_notify_method"
     */
    public function testPropertyCdrNotifyMethod()
    {
    }

    /**
     * Test attribute "cdr_notify_password"
     */
    public function testPropertyCdrNotifyPassword()
    {
    }

    /**
     * Test attribute "cdr_notify_username"
     */
    public function testPropertyCdrNotifyUsername()
    {
    }

    /**
     * Test attribute "font_family"
     */
    public function testPropertyFontFamily()
    {
    }

    /**
     * Test attribute "primary_color"
     */
    public function testPropertyPrimaryColor()
    {
    }

    /**
     * Test attribute "secondary_color"
     */
    public function testPropertySecondaryColor()
    {
    }
}
