=begin comment

FoneStorm API 2.4.0 (Thunder)

FracTEL's Middleware API

OpenAPI spec version: 2.4.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::ConferencesApi');

my $api = WWW::SwaggerClient::ConferencesApi->new();
isa_ok($api, 'WWW::SwaggerClient::ConferencesApi');

#
# create_conference test
#
{
    my $label = undef; # replace NULL with a proper value
    my $start_time = undef; # replace NULL with a proper value
    my $end_time = undef; # replace NULL with a proper value
    my $fonenumber = undef; # replace NULL with a proper value
    my $before_message = undef; # replace NULL with a proper value
    my $after_message = undef; # replace NULL with a proper value
    my $max_members = undef; # replace NULL with a proper value
    my $result = $api->create_conference(label => $label, start_time => $start_time, end_time => $end_time, fonenumber => $fonenumber, before_message => $before_message, after_message => $after_message, max_members => $max_members);
}

#
# create_conference_1 test
#
{
    my $label = undef; # replace NULL with a proper value
    my $start_time = undef; # replace NULL with a proper value
    my $end_time = undef; # replace NULL with a proper value
    my $fonenumber = undef; # replace NULL with a proper value
    my $before_message = undef; # replace NULL with a proper value
    my $after_message = undef; # replace NULL with a proper value
    my $max_members = undef; # replace NULL with a proper value
    my $result = $api->create_conference_1(label => $label, start_time => $start_time, end_time => $end_time, fonenumber => $fonenumber, before_message => $before_message, after_message => $after_message, max_members => $max_members);
}

#
# delete_conference test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->delete_conference(id => $id);
}

#
# delete_conference_2 test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->delete_conference_2(id => $id);
}

#
# get_conference test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->get_conference(id => $id);
}

#
# get_conference_3 test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->get_conference_3(id => $id);
}

#
# get_conference_fonenumbers test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->get_conference_fonenumbers(id => $id);
}

#
# get_conference_fonenumbers_4 test
#
{
    my $id = undef; # replace NULL with a proper value
    my $result = $api->get_conference_fonenumbers_4(id => $id);
}

#
# get_conferences test
#
{
    my $result = $api->get_conferences();
}

#
# get_conferences_5 test
#
{
    my $result = $api->get_conferences_5();
}

#
# update_conference test
#
{
    my $id = undef; # replace NULL with a proper value
    my $label = undef; # replace NULL with a proper value
    my $start_time = undef; # replace NULL with a proper value
    my $end_time = undef; # replace NULL with a proper value
    my $fonenumber = undef; # replace NULL with a proper value
    my $before_message = undef; # replace NULL with a proper value
    my $after_message = undef; # replace NULL with a proper value
    my $max_members = undef; # replace NULL with a proper value
    my $result = $api->update_conference(id => $id, label => $label, start_time => $start_time, end_time => $end_time, fonenumber => $fonenumber, before_message => $before_message, after_message => $after_message, max_members => $max_members);
}

#
# update_conference_6 test
#
{
    my $id = undef; # replace NULL with a proper value
    my $label = undef; # replace NULL with a proper value
    my $start_time = undef; # replace NULL with a proper value
    my $end_time = undef; # replace NULL with a proper value
    my $fonenumber = undef; # replace NULL with a proper value
    my $before_message = undef; # replace NULL with a proper value
    my $after_message = undef; # replace NULL with a proper value
    my $max_members = undef; # replace NULL with a proper value
    my $result = $api->update_conference_6(id => $id, label => $label, start_time => $start_time, end_time => $end_time, fonenumber => $fonenumber, before_message => $before_message, after_message => $after_message, max_members => $max_members);
}


1;
