=begin comment

FracTEL API 2.1.0

No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: 2.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end comment

=cut

#
# NOTE: This class is auto generated by Swagger Codegen
# Please update the test cases below to test the API endpoints.
# Ref: https://github.com/swagger-api/swagger-codegen
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::SwaggerClient::FonenumbersApi');

my $api = WWW::SwaggerClient::FonenumbersApi->new();
isa_ok($api, 'WWW::SwaggerClient::FonenumbersApi');

#
# delete_fonenumbers_fonenumber test
#
{
    my $fonenumber = undef; # replace NULL with a proper value
    my $result = $api->delete_fonenumbers_fonenumber(fonenumber => $fonenumber);
}

#
# get_fonenumbers test
#
{
    my $filter = undef; # replace NULL with a proper value
    my $result = $api->get_fonenumbers(filter => $filter);
}

#
# get_fonenumbers_fonenumber test
#
{
    my $fonenumber = undef; # replace NULL with a proper value
    my $result = $api->get_fonenumbers_fonenumber(fonenumber => $fonenumber);
}

#
# post_fonenumbers test
#
{
    my $area_code = undef; # replace NULL with a proper value
    my $result = $api->post_fonenumbers(area_code => $area_code);
}

#
# put_fonenumbers_fonenumber test
#
{
    my $fonenumber = undef; # replace NULL with a proper value
    my $type = undef; # replace NULL with a proper value
    my $value = undef; # replace NULL with a proper value
    my $url_method = undef; # replace NULL with a proper value
    my $url_username = undef; # replace NULL with a proper value
    my $url_password = undef; # replace NULL with a proper value
    my $result = $api->put_fonenumbers_fonenumber(fonenumber => $fonenumber, type => $type, value => $value, url_method => $url_method, url_username => $url_username, url_password => $url_password);
}


1;
