/**
 * FoneStorm API 2.2.0 (Breeze)
 * FracTEL's Middleware API
 *
 * OpenAPI spec version: 2.2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.2.3
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/FoneNumberFaxOptions', 'model/FoneNumberSmsOptions', 'model/FoneNumberVoiceOptions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./FoneNumberFaxOptions'), require('./FoneNumberSmsOptions'), require('./FoneNumberVoiceOptions'));
  } else {
    // Browser globals (root is window)
    if (!root.FoneStormApi220Breeze) {
      root.FoneStormApi220Breeze = {};
    }
    root.FoneStormApi220Breeze.FoneNumber = factory(root.FoneStormApi220Breeze.ApiClient, root.FoneStormApi220Breeze.FoneNumberFaxOptions, root.FoneStormApi220Breeze.FoneNumberSmsOptions, root.FoneStormApi220Breeze.FoneNumberVoiceOptions);
  }
}(this, function(ApiClient, FoneNumberFaxOptions, FoneNumberSmsOptions, FoneNumberVoiceOptions) {
  'use strict';




  /**
   * The FoneNumber model module.
   * @module model/FoneNumber
   * @version 2.2.0
   */

  /**
   * Constructs a new <code>FoneNumber</code>.
   * @alias module:model/FoneNumber
   * @class
   * @param fonenumber {String} FoneNumber.
   */
  var exports = function(fonenumber) {
    var _this = this;

    _this['fonenumber'] = fonenumber;






  };

  /**
   * Constructs a <code>FoneNumber</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/FoneNumber} obj Optional instance to populate.
   * @return {module:model/FoneNumber} The populated <code>FoneNumber</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('fonenumber')) {
        obj['fonenumber'] = ApiClient.convertToType(data['fonenumber'], 'String');
      }
      if (data.hasOwnProperty('state')) {
        obj['state'] = ApiClient.convertToType(data['state'], 'String');
      }
      if (data.hasOwnProperty('rate_center')) {
        obj['rate_center'] = ApiClient.convertToType(data['rate_center'], 'String');
      }
      if (data.hasOwnProperty('is_active')) {
        obj['is_active'] = ApiClient.convertToType(data['is_active'], 'String');
      }
      if (data.hasOwnProperty('sms_options')) {
        obj['sms_options'] = FoneNumberSmsOptions.constructFromObject(data['sms_options']);
      }
      if (data.hasOwnProperty('voice_options')) {
        obj['voice_options'] = FoneNumberVoiceOptions.constructFromObject(data['voice_options']);
      }
      if (data.hasOwnProperty('fax_options')) {
        obj['fax_options'] = FoneNumberFaxOptions.constructFromObject(data['fax_options']);
      }
    }
    return obj;
  }

  /**
   * FoneNumber.
   * @member {String} fonenumber
   */
  exports.prototype['fonenumber'] = undefined;
  /**
   * US State for fonenumber.
   * @member {String} state
   */
  exports.prototype['state'] = undefined;
  /**
   * Rate center for fonenumber.
   * @member {String} rate_center
   */
  exports.prototype['rate_center'] = undefined;
  /**
   * Status of FoneNumber.
   * @member {String} is_active
   */
  exports.prototype['is_active'] = undefined;
  /**
   * @member {module:model/FoneNumberSmsOptions} sms_options
   */
  exports.prototype['sms_options'] = undefined;
  /**
   * @member {module:model/FoneNumberVoiceOptions} voice_options
   */
  exports.prototype['voice_options'] = undefined;
  /**
   * @member {module:model/FoneNumberFaxOptions} fax_options
   */
  exports.prototype['fax_options'] = undefined;



  return exports;
}));


