<?php
/**
 * ConferencesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FoneStorm API 2.4.0 (Thunder)
 *
 * FracTEL's Middleware API
 *
 * OpenAPI spec version: 2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * ConferencesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ConferencesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createConference
     *
     * Create Conference.
     *
     */
    public function testCreateConference0()
    {
    }

    /**
     * Test case for createConference_0
     *
     * Create Conference.
     *
     */
    public function testCreateConference0()
    {
    }

    /**
     * Test case for deleteConference
     *
     * Delete Conference.
     *
     */
    public function testDeleteConference0()
    {
    }

    /**
     * Test case for deleteConference_0
     *
     * Delete Conference.
     *
     */
    public function testDeleteConference0()
    {
    }

    /**
     * Test case for getConference
     *
     * Get Conference.
     *
     */
    public function testGetConference0()
    {
    }

    /**
     * Test case for getConferenceFonenumbers
     *
     * Conference Fonenumbers.
     *
     */
    public function testGetConferenceFonenumbers0()
    {
    }

    /**
     * Test case for getConferenceFonenumbers_0
     *
     * Conference Fonenumbers.
     *
     */
    public function testGetConferenceFonenumbers0()
    {
    }

    /**
     * Test case for getConference_0
     *
     * Get Conference.
     *
     */
    public function testGetConference0()
    {
    }

    /**
     * Test case for getConferences
     *
     * Get Conferences.
     *
     */
    public function testGetConferences0()
    {
    }

    /**
     * Test case for getConferences_0
     *
     * Get Conferences.
     *
     */
    public function testGetConferences0()
    {
    }

    /**
     * Test case for updateConference
     *
     * Update Conference.
     *
     */
    public function testUpdateConference0()
    {
    }

    /**
     * Test case for updateConference_0
     *
     * Update Conference.
     *
     */
    public function testUpdateConference0()
    {
    }
}
