<?php
/**
 * DocumentsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * FoneStorm API 2.4.0 (Thunder)
 *
 * FracTEL's Middleware API
 *
 * OpenAPI spec version: 2.4.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiClient;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DocumentsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createDocument
     *
     * Create Document.
     *
     */
    public function testCreateDocument0()
    {
    }

    /**
     * Test case for createDocument_0
     *
     * Create Document.
     *
     */
    public function testCreateDocument0()
    {
    }

    /**
     * Test case for deleteDocument
     *
     * Delete Document.
     *
     */
    public function testDeleteDocument0()
    {
    }

    /**
     * Test case for deleteDocument_0
     *
     * Delete Document.
     *
     */
    public function testDeleteDocument0()
    {
    }

    /**
     * Test case for getDocument
     *
     * Get Document.
     *
     */
    public function testGetDocument0()
    {
    }

    /**
     * Test case for getDocument_0
     *
     * Get Document.
     *
     */
    public function testGetDocument0()
    {
    }

    /**
     * Test case for getDocuments
     *
     * Get Documents.
     *
     */
    public function testGetDocuments0()
    {
    }

    /**
     * Test case for getDocuments_0
     *
     * Get Documents.
     *
     */
    public function testGetDocuments0()
    {
    }

    /**
     * Test case for updateDocument
     *
     * Update Document.
     *
     */
    public function testUpdateDocument0()
    {
    }

    /**
     * Test case for updateDocument_0
     *
     * Update Document.
     *
     */
    public function testUpdateDocument0()
    {
    }
}
