=begin
FoneStorm API 2.4.0 (Thunder)

FracTEL's Middleware API

OpenAPI spec version: 2.4.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end
class FaxesController < ApplicationController

  def configure_fax_receive_notify
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def configure_fax_receive_notify_1
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def configure_fax_send_notify
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def configure_fax_send_notify_2
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end

  def create
    # Your code here

    render json: {"message" => "yes, it worked"}
  end
end
