=begin
#FoneStorm API 2.2.0

#Extended API Documentation: https://developer.fonestorm.com

OpenAPI spec version: 2.2.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

module SwaggerClient
  VERSION = "1.0.0"
end
