=begin
FoneStorm API 2.4.0 (Thunder)

FracTEL's Middleware API

OpenAPI spec version: 2.4.0

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end


class InlineResponse200 < ApplicationRecord

  serialize :conferences, Array
end
