/*
 * FoneStorm API 2.2.0 (Breeze)
 * FracTEL's Middleware API
 *
 * OpenAPI spec version: 2.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CallToAction
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-12-20T17:03:53.264-07:00")
public class CallToAction {
  @SerializedName("id")
  private String id = null;

  @SerializedName("account_id")
  private String accountId = null;

  @SerializedName("name")
  private String name = null;

  public CallToAction id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Unique identifier of call to action.
   * @return id
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of call to action.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CallToAction accountId(String accountId) {
    this.accountId = accountId;
    return this;
  }

   /**
   * Unique identifier of associated account.
   * @return accountId
  **/
  @ApiModelProperty(value = "Unique identifier of associated account.")
  public String getAccountId() {
    return accountId;
  }

  public void setAccountId(String accountId) {
    this.accountId = accountId;
  }

  public CallToAction name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Name of call to action.
   * @return name
  **/
  @ApiModelProperty(value = "Name of call to action.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CallToAction callToAction = (CallToAction) o;
    return Objects.equals(this.id, callToAction.id) &&
        Objects.equals(this.accountId, callToAction.accountId) &&
        Objects.equals(this.name, callToAction.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, accountId, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CallToAction {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

